@token = 1|RvOwCVYDAUZtyLuhBRlZDfl77BobgENRSiMfsDJH9c8dcbb0

### REGISTER
POST http://laravel-blog.test/api/register
Content-Type: application/json
Accept: application/json

{
  "name": "edmo farias",
  "email": "edmofarias@gmail.com",
  "password": "123456",
  "password_confirmation": "123456"
}

###LOGIN
POST http://laravel-blog.test/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "edmofarias@gmail.com",
  "password": "123456"
}

### LOGOUT
POST http://laravel-blog.test/api/logout
Content-Type: application/json
Authorization: Bearer {{token}}

#-------------------------------------------------------------------------------------

### CREATE POST
POST http://laravel-blog.test/api/posts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "My First Post22222222",
  "content": "This is the content"
}

### LIST ALL POST
GET http://laravel-blog.test/api/posts
Content-Type: application/json

### SINGLE POST
GET http://laravel-blog.test/api/posts/1
Content-Type: application/json

### USER POSTS
GET http://laravel-blog.test/api/posts/users/15
Accept: application/json

### UPDATE POST
PUT http://laravel-blog.test/api/posts/19
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "UPDATED POST TITLE",
  "content": "This is the content"
}
#-------------------------------------------------------------------------------------

### CREATE COMMENT
POST http://laravel-blog.test/api/posts/1/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "FIRST COMMENT"
}

### LIST COMMENT
GET http://laravel-blog.test/api/posts/1/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "GREAT Great post!2222222"
}

### UPDATE COMMENT
PUT http://laravel-blog.test/api/comments/21
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "GREAT Great post!2222222"
}